name: kiwi
description: "智能知识问答，提升企业效率"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # 状态管理
  provider: ^6.1.1
  # 网络请求
  http: ^1.1.0
  # 函数式编程
  dartz: ^0.10.1
  # 依赖注入
  get_it: ^7.6.4
  logger: ^2.5.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3 # Added shared_preferences
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  either_dart: ^1.0.0
  file_picker: ^10.1.9
  path: ^1.9.0
  crypto: ^3.0.3
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
